name: dportfolio_v2
description: Dportfolio app in Flutter V2.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_hooks: ^0.18.1
  flutter_bloc: ^8.0.0
  injectable: ^1.5.0
  get_it: ^7.2.0
  freezed_annotation: ^1.0.0
  pref: ^2.4.0
  auto_route: ^2.4.0
  fluttericon: ^2.0.0
  webview_flutter: ^2.3.1
  url_launcher: ^6.0.15
  package_info: ^2.0.2
  platform_info: ^3.1.0
  # either type and etc.
  dartz: ^0.10.0

  provider: ^6.0.1
  chopper: ^4.0.3
  sticky_headers: ^0.2.0
  photo_view: ^0.13.0
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  build_runner: ^2.1.5
  auto_route_generator: ^2.4.0
  injectable_generator: ^1.5.0
  chopper_generator: ^4.0.3
  built_value_generator: ^8.1.3
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1
  lint: ^1.7.2

flutter_app_name:
  name: "Dportfolio"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/portfolio/dportfolio/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ComicSansMs
      fonts:
        - asset: fonts/comic_sans_ms.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
