name: dportfolio_v2
description: Dportfolio app in Flutter V2.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_hooks: ^0.14.1
  flutter_bloc: ^6.0.6
  injectable: ^1.0.7
  get_it: ^5.0.3
  freezed_annotation: ^0.12.0
  preferences: ^5.2.1
  auto_route: ^0.6.9
  flutter_icons: ^1.1.0
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  package_info: ^0.4.3+2
  platform_info: ^2.2.0
  # either type and etc.
  dartz: ^0.9.2
  provider: ^4.3.2+4
  chopper: ^3.0.6
  sticky_headers: ^0.1.8+1
  photo_view: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  build_runner: ^1.10.2
  auto_route_generator: ^0.6.9
  injectable_generator: ^1.0.0
  chopper_generator: ^3.0.5
  built_value_generator: ^7.1.0
  flutter_native_splash: ^0.2.9
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: "^0.0.1"
  lint: ^1.3.0

flutter_launcher_name:
  name: "Dportfolio"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/portfolio/dportfolio/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ComicSansMs
      fonts:
        - asset: fonts/comic_sans_ms.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
